# Generated by Django 2.2.7 on 2019-12-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('originalPrice', models.CharField(max_length=50)),
                ('salePrice', models.CharField(max_length=50)),
            ],
        ),
    ]
