# Generated by Django 2.2.7 on 2019-12-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrwalingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(max_length=2)),
                ('isbn', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('originalPrice', models.CharField(max_length=50)),
                ('salePrice', models.CharField(max_length=50)),
            ],
        ),
    ]
